ViewModels/PedidoViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using Cadeteria.Models;

namespace Cadeteria.ViewModels
{
    public class PedidoViewModel
    {
        public int Nro { get; set; }
        public string Detalles { get; set; }
        public ClienteViewModel Cliente { get; set; }
        public CadeteViewModel Cadete { get; set; }
        public estado Estado { get; set; }

        public PedidoViewModel()
        {

        }

        public PedidoViewModel(int num, string detalles, ClienteViewModel cliente, CadeteViewModel cadete = null, estado estado = estado.SinAsignar)
        {
            Nro = num;
            Detalles = detalles;
            Cliente = cliente;
            Estado = estado;
            Cadete = cadete;
        }

        public string ObtenerEstado()
        {
            if (Estado == estado.SinAsignar) return "Sin asignar";
            else if (Estado == estado.Pendiente) return "Pendiente";
            else if (Estado == estado.EnCurso) return "En curso";
            else if (Estado == estado.Entregado) return "Entregado";
            else return "Indefinido";
        }

        static public bool operator ==(PedidoViewModel ped1, PedidoViewModel ped2)
        {
            return ped1.Nro == ped2.Nro;
        }

        static public bool operator !=(PedidoViewModel ped1, PedidoViewModel ped2)
        {
            return ped1.Nro != ped2.Nro;
        }
    }

    public class CrearPedidoViewModel
    {
        [AllowNull]
        [DisplayName("Detalles")]
        public string Detalles { get; set; }

        [Required]
        [DisplayName("ID")]
        public int ClienteID { get; set; }

        public bool NuevoCliente { get; set; }

        [AllowNull]
        [DisplayName("Nombre")]
        public string? ClienteNombre { get; set; }

        [AllowNull]
        [DisplayName("Dirección")]
        public string? ClienteDireccion { get; set; }

        [AllowNull]
        [DisplayName("Teléfono")]
        public string? ClienteTelefono { get; set; }

        public CrearPedidoViewModel()
        {

        }

        public CrearPedidoViewModel(string detalles, int id)
        {
            Detalles = detalles;
            ClienteID = id;
        }
    }
}

Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using Cadeteria.Models;
using Cadeteria.ViewModels;
using Cadeteria.Repo;
using AutoMapper;

namespace Cadeteria.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository PedidoRepo;
        private readonly ICadeteRepository CadeteRepo;
        private readonly IClienteRepository ClienteRepo;
        private readonly IMapper mapper;

        public PedidoController(IPedidoRepository pedidoRepo, ICadeteRepository cadeteRepo, IClienteRepository clienteRepo, IMapper map)
        {
            PedidoRepo = pedidoRepo;
            CadeteRepo = cadeteRepo;
            ClienteRepo = clienteRepo;
            mapper = map;
        }

        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            // Utilizados para filtrar
            ViewData["clientes"] = mapper.Map<List<ClienteViewModel>>(ClienteRepo.ObtenerTodo());
            ViewData["cadetes"] = mapper.Map<List<CadeteViewModel>>(CadeteRepo.ObtenerTodo());

            if(HttpContext.Session.GetInt32("rol") == 2)
            {
                return View(mapper.Map<List<PedidoViewModel>>(PedidoRepo.ObtenerPorCadete((int)HttpContext.Session.GetInt32("id_cadete"))));
            }
            else
            {
                return View(mapper.Map<List<PedidoViewModel>>(PedidoRepo.ObtenerTodo()));
            }
        }

        [HttpPost]
        public ActionResult Index(int idCadete, int idCliente)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                idCadete = (int)HttpContext.Session.GetInt32("id_cadete");
            }

            ViewData["clientes"] = mapper.Map<List<ClienteViewModel>>(ClienteRepo.ObtenerTodo());
            ViewData["cadetes"] = mapper.Map<List<CadeteViewModel>>(CadeteRepo.ObtenerTodo());

            List<PedidoModel> pedidosFiltrados = new();
            List<PedidoModel> pedidosCliente;
            List<PedidoModel> pedidosCadete;

            if (idCadete == 0 && idCliente == 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                if (idCadete != 0 && idCliente != 0)
                {
                    pedidosCliente = PedidoRepo.ObtenerPorCliente(idCliente);
                    pedidosCadete = PedidoRepo.ObtenerPorCadete(idCadete);

                    foreach (var pedido1 in pedidosCliente)
                    {
                        foreach (var pedido2 in pedidosCadete)
                        {
                            if (pedido1 == pedido2)
                            {
                                pedidosFiltrados.Add(pedido1);
                                break;
                            }
                        }
                    }
                }
                else
                {
                    if (idCadete != 0)
                    {
                        pedidosFiltrados = PedidoRepo.ObtenerPorCadete(idCadete);
                    }
                    else
                    {
                        pedidosFiltrados = PedidoRepo.ObtenerPorCliente(idCliente);
                    }
                }
            }
            
            return View(mapper.Map<List<PedidoViewModel>>(pedidosFiltrados));
        }

        [HttpGet]
        public ActionResult Create()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["clientes"] = mapper.Map<List<ClienteViewModel>>(ClienteRepo.ObtenerTodo());

            return View();
        }

        [HttpPost]
        public ActionResult Create(CrearPedidoViewModel pedido)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                if (pedido.NuevoCliente)
                {
                    if (pedido.ClienteNombre != null && pedido.ClienteDireccion != null && pedido.ClienteTelefono != null)
                    {
                        PedidoRepo.CrearPedidoConCliente(mapper.Map<PedidoModel>(pedido));
                    }
                    else
                    {
                        return RedirectToAction("Error", new { error = "No se ha podido crear el cliente" });
                    }
                }
                else
                {
                    PedidoRepo.Crear(mapper.Map<PedidoModel>(pedido));
                }
                return RedirectToAction("Index");
                
            }
            else
            {
                return RedirectToAction("Error", new { error = "No se ha podido crear el pedido" });
            }
        }

        public ActionResult Details(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            var pedido = PedidoRepo.Obtener(id);

            if (pedido is not null)
            {
                return View(mapper.Map<PedidoViewModel>(pedido));
            }

            return RedirectToAction("Error", new { error = "No se ha encontrado el pedido solicitado" });
        }

        public ActionResult Delete(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            if (PedidoRepo.Borrar(id))
            {
                return RedirectToAction("Index");
            }

            else return RedirectToAction("Error", new { error = "No se ha encontrado el pedido solicitado" });
        }

        public ActionResult Estado(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            var pedido = PedidoRepo.Obtener(id);

            if (pedido is not null && pedido.Estado == estado.EnCurso)
            {
                PedidoRepo.CambiarEstado(id, estado.Entregado);
                return RedirectToAction("Index");
            }
            else return RedirectToAction("Error", new { error = "No se ha encontrado el pedido solicitado" });
        }

        public ActionResult Asignar(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            var pedido = PedidoRepo.Obtener(id);
            ViewData["cadetes"] = mapper.Map<List<CadeteViewModel>>(CadeteRepo.ObtenerTodo());

            if (pedido is not null)
            {
                return View(mapper.Map<PedidoViewModel>(pedido));
            }

            else return RedirectToAction("Error", new { error = "No se ha encontrado el pedido solicitado" });
        }

        [HttpPost]
        public ActionResult Asignar(int idp, int idc)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            if (PedidoRepo.AsignarCadete(idp, idc))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error", new { error = "No se ha podido asignar el pedido" });
            }
        }

        public ActionResult Iniciar(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            var pedido = PedidoRepo.Obtener(id);

            if (pedido is not null && pedido.Estado == estado.Pendiente)
            {
                PedidoRepo.CambiarEstado(id, estado.EnCurso);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error", new { error = "No se ha podido iniciar el pedido" });
            }
        }

        public ActionResult Error(string error)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            ViewData["error"] = error;

            return View();
        }
    }
}

Views/Pedido/Asignar.cshtml
@{
    ViewData["Title"] = "Asignar pedido";
}

@model Cadeteria.ViewModels.PedidoViewModel

<section>
    @if (((List<Cadeteria.ViewModels.CadeteViewModel>)ViewData["cadetes"]).Count > 0)
    {
        <form method="post" class="form-edit">
            <input type="number" id="idp" name="idp" value="@Model.Nro" hidden>
            <select id="idc" name="idc">
                @foreach (var cadete in (List<Cadeteria.ViewModels.CadeteViewModel>)ViewData["cadetes"])
                {
                    <option value="@cadete.ID">@cadete.Nombre</option>
                }
            </select>
            <input type="submit" value="Asignar al pedido">
        </form>
    }
    else
    {
        <h3>No hay ningún cadete para asignar</h3>
    }
</section>

Views/Pedido/Create.cshtml
@{
    ViewData["Title"] = "Crear pedido";
}

@using Cadeteria.ViewModels
@model Cadeteria.ViewModels.CrearPedidoViewModel

<section class="crear-pedido">
    <h2>Crear pedido</h2>
    <form method="post" class="form-create">
        <h4>Datos del pedido</h4>
        <label asp-for="@Model.Detalles"></label>
        <input asp-for="@Model.Detalles">

        <input asp-for="@Model.NuevoCliente" hidden>

        <h5>Cliente</h5>
        <a id="boton-cliente" href="#" onclick="manejoClientes()">Nuevo</a>

        <!-- Cliente existente -->
        <section id="selec-cliente">
        <label asp-for="@Model.ClienteID">Seleccionar</label>
        @if(((List<ClienteViewModel>)ViewData["clientes"]).Count > 0)
        {
            <select asp-for="@Model.ClienteID">
                    @foreach (var cliente in (List<ClienteViewModel>)ViewData["clientes"])
                {
                    <option value="@cliente.ID">@cliente.Nombre</option>
                }
            </select>
        }
        else
        {
            <p>No hay ningún cliente</p>
        }
        </section>

        <!-- Cliente nuevo -->
        <section id="nuevo-cliente">
            <label asp-for="@Model.ClienteNombre"></label>
            <input asp-for="@Model.ClienteNombre">

            <label asp-for="@Model.ClienteDireccion"></label>
            <input asp-for="@Model.ClienteDireccion">

            <label asp-for="@Model.ClienteTelefono"></label>
            <input asp-for="@Model.ClienteTelefono">
        </section>
        <button>Ingresar</button>
    </form>
</section>

Views/Pedido/Details.cshtml
@{
    ViewData["Title"] = "Detalles del pedido";
}
@model Cadeteria.ViewModels.PedidoViewModel

<section class="detalles-pedido">
    <h2>Detalles del pedido</h2>
    <p><strong>Número: </strong>@Model.Nro</p>
    <p><strong>Detalles: </strong>@Model.Detalles</p>
    <h4>Datos del cliente</h4>
    <p><strong>Nombre: </strong>@Model.Cliente.Nombre</p>
    <p><strong>Dirección: </strong>@Model.Cliente.Direccion</p>
    <p><strong>Teléfono: </strong>@Model.Cliente.Telefono</p>
</section>

Views/Pedido/Index.cshtml
@{
    ViewData["Title"] = "Pedidos";
}

@model List<Cadeteria.ViewModels.PedidoViewModel>
@using Microsoft.AspNetCore.Http

<h1>Pedidos</h1>

<section id="pedido-index">
    <section id="manejo-pedidos">
        <section class="crear">
        @if(Context.Session.GetInt32("rol") == 1)
        {
            <a asp-controller="Pedido" asp-action="Create">+</a>
        }
        </section>
        <a href="#" id="filtrar" onclick="filtrosPedidos()">Filtrar</a>
    </section>
    
    <section id="filtrar-pedidos">
        <form method="post">
            @if(Context.Session.GetInt32("rol") == 1)
            {
                <label for="filtrar-cadete">Cadete
                <select name="idCadete" id="filtrar-cadete">
                    <option value="0">Cualquier cadete</option>
                    @foreach(var cadete in (List<Cadeteria.ViewModels.CadeteViewModel>)ViewData["cadetes"])
                    {
                        <option value="@cadete.ID">@cadete.Nombre</option>
                    }
                </select>
                </label>
            }
            <label for="filtrar-cliente">
                Cliente
            <select name="idCliente" id="filtrar-cliente">
                <option value="0">Cualquier cliente</option>
                    @foreach (var cliente in (List<Cadeteria.ViewModels.ClienteViewModel>)ViewData["clientes"])
                {
                    <option value="@cliente.ID">@cliente.Nombre</option>
                }
            </select>
            </label>
            <button>Aplicar</button>
        </form>
    </section>
    

    <section class="pedidos">
        @if(Model.Count > 0)
        {
            <table>
                <thead>
                <th>Detalles</th>
                <th>Estado</th>
                <th>Cadete</th>
                <th>Acciones</th>
                </thead>
                <tbody>
                    @foreach (var pedido in Model)
                    {
                        <tr>
                            <td>@pedido.Detalles</td>
                            <td>@pedido.ObtenerEstado()</td>
                            @if (pedido.Cadete is null)
                            {
                                <td>-</td>
                            }
                            else
                            {
                                <td>@pedido.Cadete.Nombre</td>
                            }

                            <td>
                                <section class="table-botones">
                                    @if (pedido.Estado == estado.SinAsignar && Context.Session.GetInt32("rol") == 1)
                                    {
                                        <a asp-controller="Pedido" asp-action="Asignar" asp-route-id="@pedido.Nro" class="pedido-asignar">Asignar</a>
                                    }
                                    @if (pedido.Estado == estado.Pendiente)
                                    {
                                        <a asp-controller="Pedido" asp-action="Iniciar" asp-route-id="@pedido.Nro" class="pedido-asignar">Iniciar Pedido</a>
                                        @if (Context.Session.GetInt32("rol") == 1)
                                        {
                                            <a asp-controller="Pedido" asp-action="Asignar" asp-route-id="@pedido.Nro" class="pedido-asignar">Reasignar</a>
                                        }
                                    }
                                    @if (pedido.Estado == estado.EnCurso)
                                    {
                                        <a asp-controller="Pedido" asp-action="Estado" asp-route-id="@pedido.Nro" class="pedido-estado">Entregar</a>
                                    }
                                    @if(Context.Session.GetInt32("rol") == 1)
                                    {
                                        <a asp-controller="Pedido" asp-action="Delete" asp-route-id="@pedido.Nro" class="pedido-borrar">Borrar</a>
                                    }
                                    <a asp-controller="Pedido" asp-action="Details" asp-route-id="@pedido.Nro" class="pedido-detalles">Detalles</a>
                                </section>
                            </td>
                            
                            

                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h3>No existe ningún pedido</h3>
        }
    
    </section>
</section>