ViewModels/CadeteViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

namespace Cadeteria.ViewModels
{
    public class CadeteViewModel
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }

        public CadeteViewModel()
        {

        }
        public CadeteViewModel(int id, string nombre, string direccion, string telefono)
        {
            this.ID = id;
            this.Nombre = nombre;
            this.Direccion = direccion;
            this.Telefono = telefono;
        }

        static public bool operator ==(CadeteViewModel cad1, CadeteViewModel cad2)
        {
            return cad1.ID == cad2.ID;
        }

        static public bool operator !=(CadeteViewModel cad1, CadeteViewModel cad2)
        {
            return cad1.ID != cad2.ID;
        }
    }

    public class CrearCadeteViewModel
    {
        public int ID { get; set; }

        [Required]
        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [Required]
        [DisplayName("Teléfono")]
        public long Telefono { get; set; }

        [Required]
        [StringLength(80)]
        [DisplayName("Dirección")]
        public string Direccion { get; set; }

        public CrearCadeteViewModel()
        {

        }

        public CrearCadeteViewModel(string nombre, long telefono, string direccion)
        {
            Nombre = nombre;
            Telefono = telefono;
            Direccion = direccion;
        }
    }

    public class EditarCadeteViewModel
    {
        [Required]
        [NotNull]
        public int ID { get; set; }

        [Required]
        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [Required]
        [DisplayName("Teléfono")]
        public long Telefono { get; set; }

        [Required]
        [StringLength(80)]
        [DisplayName("Dirección")]
        public string Direccion { get; set; }

        public EditarCadeteViewModel()
        {

        }
        public EditarCadeteViewModel(int iD, string nombre, long tel, string direccion)
        {
            ID = iD;
            Nombre = nombre;
            Telefono = tel;
            Direccion = direccion;
        }
    }
}

Controllers/CadeteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Cadeteria.Models;
using Cadeteria.ViewModels;
using Microsoft.Data.Sqlite;
using Cadeteria.Repo;
using Microsoft.AspNetCore.Session;
using AutoMapper;

namespace Cadeteria.Controllers
{
    public class CadeteController : Controller
    {
        private readonly ICadeteRepository CadeteRepo;
        private readonly IMapper mapper;

        public CadeteController(ICadeteRepository cadeteRepo, IMapper map)
        {
            CadeteRepo = cadeteRepo;
            mapper = map;
        }

        // GET: CadeteController
        public ActionResult Index()
        {
            List<CadeteViewModel> cadetes = new List<CadeteViewModel>();

            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            foreach (var cadete in CadeteRepo.ObtenerTodo())
            {
                cadetes.Add(mapper.Map<CadeteViewModel>(cadete));
            }

            return View(cadetes);
        }

        public ActionResult Sesion()
        {
            return View();
        }

        public ActionResult Error(string error)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["error"] = error;
            return View();
        }

        // GET: CadeteController/Create
        public ActionResult Create()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        // POST: CadeteController/Create
        [HttpPost]
        public ActionResult Create(CrearCadeteViewModel cadete)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                CadeteRepo.Crear(mapper.Map<CadeteModel>(cadete));
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error", new { error = "No se ha podido crear el cadete" });
            }
        }

        // GET: CadeteController/Edit/5
        public ActionResult Edit(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            var cadete = CadeteRepo.Obtener(id);

            if (cadete is not null)
            {
                return View(mapper.Map<EditarCadeteViewModel>(cadete));
            }
            else
            {
                return RedirectToAction("Error", new {error = "No se ha encontrado el cadete solicitado"});
            }
        }

        // POST: CadeteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EditarCadeteViewModel cadete)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                CadeteRepo.Actualizar(mapper.Map<CadeteModel>(cadete));
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Error", new { error = "No se ha editar el cadete" });
            }

        }

        // GET: CadeteController/Delete/5
        public ActionResult Delete(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("name")))
            {
                return RedirectToAction("Index", "Logging");
            }

            if (HttpContext.Session.GetInt32("rol") != 1)
            {
                return RedirectToAction("Index", "Home");
            }

            if (CadeteRepo.Borrar(id)) return RedirectToAction("Index");
            else return RedirectToAction("Error", new { error = "Ocurrió un error al intentar borrar el cadete" });
        }
    }
}

Views/Cadete/Create.cshtml
@{
    ViewData["Title"] = "Crear cadete";
}

@model Cadeteria.ViewModels.CrearCadeteViewModel

<section class="crear-cadete">
    <h2>Crear cadete</h2>
    <form method="post" class="form-create">
        <h3>Datos del cadete</h3>
        <input asp-for="@Model.ID" value="0" hidden>
        <label asp-for="@Model.Nombre"></label>
        <input asp-for="@Model.Nombre">
        <label asp-for="@Model.Direccion"></label>
        <input asp-for="@Model.Direccion">
        <label asp-for="@Model.Telefono"></label>
        <input asp-for="@Model.Telefono">
        <button>Ingresar</button>
    </form>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Cadete/Edit.cshtml
@{
    ViewData["Title"] = "Editar cadete";
}

@model Cadeteria.ViewModels.EditarCadeteViewModel

<section class="editar-cadete">
    <h2>Editar cadete</h2>
    <form method="post" class="form-edit">
        <h3>Datos del cadete</h3>
        <input asp-for="@Model.ID" value="@Model.ID" hidden>
        <label asp-for="@Model.Nombre"></label>
        <input asp-for="@Model.Nombre" value="@Model.Nombre">
        <label asp-for="@Model.Direccion"></label>
        <input asp-for="@Model.Direccion" value="@Model.Direccion">
        <label asp-for="@Model.Telefono"></label>
        <input asp-for="@Model.Telefono" value="@Model.Telefono">
        <button>Editar</button>
    </form>
</section>

Views/Cadete/Index.cshtml
@{
    ViewData["Title"] = "Ver cadetes";
}

@using Cadeteria.ViewModels

@model List<CadeteViewModel>

<h1>Cadetes</h1>
<section id="cadete-index">
    <section class="crear">
        <a asp-controller="Cadete" asp-action="Create">+</a>
    </section>
    <section class="cadetes">
        @if (Model.Count > 0)
        {
            <table>
                <thead>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Acciones</th>
                </thead>
                <tbody>
                    @foreach (var cadete in Model)
                    {
                        <tr>
                            <td>@cadete.Nombre</td>
                            <td>@cadete.Direccion</td>
                            <td>@cadete.Telefono</td>
                            <td><section class="table-botones"><a href="/Cadete/Edit/@cadete.ID" class="cadete-editar">Editar</a><a href="/Cadete/Delete/@cadete.ID" class="cadete-borrar">Borrar</a></section></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <h3>No existe ningún cadete</h3>
        }

        </section>
</section>

Views/Cadete/Sesion.cshtml
@{
    ViewData["Title"] = "Sesiones";
}
@using Microsoft.AspNetCore.Http

<h1>Sesiones</h1>
<section id="sesiones">
    <p><strong>Username:</strong> @Context.Session.GetString("name")</p>
    <p><strong>Rol:</strong> @Context.Session.GetInt32("rol")</p>
</section>